spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    platform: postgres
    initialization-mode: always
    url: jdbc:postgresql://dpg-cf85uf1a6gdpabamc4a0-a.frankfurt-postgres.render.com:5432/weather_station
    username: weather_station_user
    password: t30CF5X6m5fSGFiL2MOgwWNg4gbCjOxg
    driver-class-name: org.postgresql.Driver
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  firebase-configuration-file: firebase/serviceAccountKey.json
  firebase-database-url: https://weather-station-714d9.firebaseio.com
  google-cloud-platform-key: AIzaSyC5iJ-5_UHz57vfnVrxPhPeejRuSmr4h2A
